In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
np.ones([2,2], dtype=np.int_)

array([[1, 1],
       [1, 1]])

In [5]:
np.ones([3,2], dtype=np.float_)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
X = np.arange(4, dtype=np.int_)

np.ones_like(X)

array([1, 1, 1, 1])

In [7]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int_)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [8]:
np.ones([4,4], dtype=np.int_) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
X = np.array([[2,3], [6,2]], dtype=np.int_)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

In [10]:
# np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# randn generates random value from a standard normal distribution 
# vs rand from a uniform distribution 
np.random.randn(3, 3, 3)

array([[[-0.09492616, -0.93444244, -0.23177843],
        [ 0.27310579,  0.42762752,  0.26206445],
        [-1.01011309,  1.29823586,  2.0542342 ]],

       [[ 1.07549065, -1.74943912,  0.29199447],
        [ 0.33305447,  0.05523296,  0.1827001 ],
        [ 0.48719765, -0.77168605,  0.20937902]],

       [[ 0.86670802,  0.07752249,  0.45912414],
        [ 0.01689972,  0.06604929,  0.46417593],
        [ 0.85372463,  0.46518921, -0.3237148 ]]])

In [12]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [13]:
X = np.array([5,2,3], dtype=np.int_)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 125280704923088
[5 2 3] 125280704923472


In [14]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [16]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [17]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [19]:
X = np.array(['A','B','C','D','E'])

X[0]

'A'

In [20]:
X[-1]

'E'

In [21]:
X[:3]

array(['A', 'B', 'C'], dtype='<U1')

In [22]:
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [23]:
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [24]:
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [25]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

In [26]:
X[-1]

array([13, 14, 15, 16])

In [27]:
X[0, 0]

1

In [28]:
X[-1, -1]

16

In [29]:
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

In [30]:
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [31]:
X[2:, 2:]

array([[11, 12],
       [15, 16]])

In [32]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float_)

array([-5., -3.,  0., 10., 40.])

In [33]:
X = np.array([0, 10, -5, 40, -3])

X.sort()
X

array([-5, -3,  0, 10, 40])

In [34]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [35]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

In [36]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.ones(4)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [37]:
X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  0]])

In [38]:
X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 6,  6,  6,  5]])

In [39]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [40]:
X[X < 0]

array([-1, -4, -9])

In [41]:
X[X > 5]

array([ 6, 10])

In [42]:
X[X > X.mean()]

array([ 2,  5,  6, 10])

In [43]:
X[(X == 2) | (X == 10)]

array([ 2, 10])

In [44]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all() # True if zeroes not in the array

False

In [45]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any() # True if zeroes in the array

True

In [46]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

X.sum()

43

In [47]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

X.mean()

3.7

In [48]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

In [49]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

In [50]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

10